# Generated by Codex on 2026-03-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mediafile_message_playlist_playlistitem_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('playing', 'Играет'), ('done', 'Завершен')], default='queued', max_length=20)),
                ('enqueued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_broadcast_items', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_queue_items', to='app.mediafile')),
            ],
            options={
                'ordering': ['enqueued_at', 'id'],
            },
        ),
    ]
