# Generated by Django 6.0.3 on 2026-03-21 00:54

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_broadcastqueueitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=app.models.media_upload_path, validators=[app.models.validate_audio_file]),
        ),
    ]
