# Generated by Django 6.0.3 on 2026-03-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mediafile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='is_shufle',
            new_name='is_shuffle',
        ),
    ]
